### ISSUE TITLE
access control

### ISSUE THREAD

**Issue by dj1an** [simonyiszk/rtl_mus#2]
Thanks, for developing this useful tool.
Working stable for days now.

How can i set access control, so that only localhost client can change parameters and external clients can not?

**Comment by ha7ilm** [comment]
It is not implemented, but you might add it easily with some lines of python. 

I did not try it yet, but I would insert something like this after line 308 in rtl_mus.py ([here](https://github.com/simonyiszk/rtl_mus/blob/master/rtl_mus.py#L308)):

``` python
if client.socket[1][0]!="127.0.0.1": return 0
```

**Comment by dj1an** [comment]
works, thanks a lot!
I think it's time to get more familiar with python coding...

**Comment by ha7ilm** [comment]
Great!
