### ISSUE TITLE
Define a specific device

### ISSUE THREAD

**Issue by SA7BNT** [simonyiszk/rtl_mus#4]
Hey thanks for this tool.

Is or how is it possible to define a specific RTL-SDR device if there are running 2 devices at the same machine?

73 
Tim de SA7BNT

**Comment by ha7ilm** [comment]
Yes, using command line flags of `rtl_tcp`.

This tool is somewhat obsolete, I advise you check out `nmux`in `csdr` if
you want a faster one (however, that cannot forward commands).
