### ISSUE TITLE
direct sampling documentation

### ISSUE THREAD

**Issue by o8ko8k** [simonyiszk/rtl_mus#5]
provide more instructions on tailoring...Permissions on commands

By changing the source code, one can easily allow and deny remote clients execute particular commands on the rtl_tcp server. Commands that are not allowed are simply not forwarded by rtl_mus.

My example:
grep -Hrn "direct sampl"
rtl_mus.py:341:         log.debug("deny: set direct sampling")
config_rtl.py:23:send_first=chr(9)+chr(0)+chr(0)+chr(0)+chr(1) # set direct sampling

How do i modify this?  I would like to allow or just hard-code set direct sampling to 1 or 2 (not zero, to force rtl_sdr to run on HF bands. thanks!

**Comment by ha7ilm** [comment]
Take a look at the `rtl_tcp.c` in RTL-SDR drivers' source code package to understand. I think you can set direct sampling mode to 2 by changing `chr(1)` to `chr(2)` but not sure.

Note that this project is obsolete so I'm closing and archiving this.
